query Trip ($id: ID!) {
  Trip(id: $id) {
    id
    name
    memberships {
      name
      email
    }
    lineItems {
      id
      type
      arrivingAirline
      arrivingAirport
      arriveAt
      departingAirline
      departingAirport
      departAt
      cost
    }
  }
}
